### ISSUE TITLE
can't handle nested media rules?

### ISSUE THREAD

**Issue by pkyeck** [konitter/gulp-combine-media-queries#7]
I have something like this

``` css
@media only screen and (max-width: 940px) {
  .test {
    background-color: red;
  }

  @media (min-resolution: 144dpi) {
    .test {
      background-color: green;
    }
  }
}

@media (min-resolution: 144dpi) {
  .test {
    background-color: yellow;
  }
}
```

but this gets converted to

``` css
@media (min-resolution: 144dpi) {
  .test {
    background-color: yellow;
  }
}

@media only screen and (max-width: 940px) {
  .test {
    background-color: red;
  }
}
```

so I'll lose my nested media rules :(

**Comment by fesor** [comment]
CSS doesn't allow to use nested media queries. You should use `and` operator. Also you may want to use CSS preprocessors like LESS or SASS:

``` css
@media only screen and (max-width: 940px) {
  .test {
    background-color: red;
  }

  @media (min-resolution: 144dpi) {
    .test {
      background-color: green;
    }
  }
}

@media (min-resolution: 144dpi) {
  .test {
    background-color: yellow;
  }
}
```

Less will compile it to

``` css
@media only screen and (max-width: 940px) {
  .test {
    background-color: red;
  }
}
@media only screen and (max-width: 940px) and (min-resolution: 144dpi) {
  .test {
    background-color: green;
  }
}
@media (min-resolution: 144dpi) {
  .test {
    background-color: yellow;
  }
}

```
